apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  labels:
    app: app
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
