apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app-image
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: app-env
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /app/data
            name: app-data
      volumes:
        - name: app-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: local-path
                resources:
                  requests:
                    storage: 500Mi