apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "db-image"
    newName: "postgres"
    newTag: "12.4"

resources:
  - namespace.k8s.yaml
  - db.stateful.k8s.yaml
  - db.svc.k8s.yaml
  - app.deploy.k8s.yaml
  - app.svc.k8s.yaml
