version: "3.4"

services:
  db:
    image: postgres:12.4
    restart: on-failure
    environment:
      - POSTGRES_USER=yeboster
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
