apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
spec:
  tls:
    - secretName: yeboster-tls
      hosts:
        - yeboster.me
  rules:
    - host: yeboster.me
      http:
        paths:
          - path: /
            backend:
              serviceName: app
              servicePort: 80
