apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../bases/common"

# Specify namespace for scoped configmaps
namespace: yeboster
configMapGenerator:
  - name: app-env
    envs:
      - ./secrets/app.env
  - name: database-env
    envs:
      - ./secrets/database.env

images:
  - name: "app-image"
    newName: "registry.container-registry/yeboster/yeboster.me"
  - name: "app-image-builder"
    newName: "registry.container-registry/yeboster/yeboster.me"
    newTag: "builder"

# patchesStrategicMerge:
#   - "patch.app.deploy.k8s.yml"

resources:
  - "ingress.k8s.yml"
  - "pipeline.k8s.yml"
  - "pipeline-run.k8s.yml"
  # NOTE: Used only for mix
  # - "app-console.deploy.k8s.yml"
