apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yeboster
bases:
  - ../../bases/common
images:
  - name: app-image
    newName: yeboster/yeboster.com
    newTag: '1.0.3'
resources:
  - ingress.k8s.yaml
  - secrets/app.sops.yaml
  - secrets/database.sops.yaml
