# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-env
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:cWXOw4TYsZhTX/2PAKw19toRO7/y1ZFn06hQVsvCTF5A79eWXBCmXp8MiNmecMr+J2psWQIodRNIfH3O2Kwh/Pj3Yb4Cdh4QHfCd,iv:S6hz8y/cijOF8v0PK6Agie3B1tkeyUcxzHnnaq6Ez7g=,tag:aIzwldNQvzx/vj5NDv20vA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:d/gIyDPUVlWfm9gNwoFlW/J8hpHHq4j21lS4f01n6FeJnYKoYJNMKPpUMTDJ7FXUxlbOdPonOmqaOQCz45yFFg==,iv:9h9KDCw2dSoBsWk/X9wheBZsq2mFsYFAeucHCaO7VaQ=,tag:xMSFXD+r76QxKEaW/EOLVg==,type:str]
    LIVE_VIEW_SIGNING_SALT: ENC[AES256_GCM,data:9hhuY28mLOC01Ug42fh1Dg==,iv:1bPechwKC+2SkNmzr3KVehw7YTTjInV5dE6e0vy7wK8=,tag:CDzB73Y2bVvimUxen6ntBA==,type:str]
    APP_DATA_PATH: ENC[AES256_GCM,data:PcfXflAYiG1G,iv:Pg4vjx1/zQciTjGaNyoWZcA+tCAnvpWsODpZKmNBkY0=,tag:FuIKf7u6k+f20V5zC9P5dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zy2rt7cnlaqg9r85w8d88zstjljcpr5cwnx35vp96l4nkzf9e9mqfqenvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0xjSVdac085ZThmV1ZB
            d0V4bEZQY3hvSlN4cjNGNXFMWVE5dVBvb0E0CndiQVN3dTUyZVVOMS8xOXpEa0p3
            bGluSUNrVGZIa1hZTTAwMXJtZjFBUmsKLS0tIFlpWnJ5WWpQU1YzbE9WY0U1YWY5
            dkFuNlQ0SStHYlo4TGFzY2lNSHY0OGMKWyrjrDVEUEEEJbEEiZuKPrVXO5k3urd7
            cY1b5AWhq8U2D2EwvbiwwURBRvLqBeDsZ8C10/sElzit3InCOjS7CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T19:09:50Z"
    mac: ENC[AES256_GCM,data:iha8UGe1ZGp3fNx/YRCbihFEYfZrLLvJuaV86E2euRxPIgrlEkShgTsU5JryQjiAyQC7AE4A7JlmA3z28owvirdr2M+pJ46aTx53mL7gNQ06YQPEcR9DucCjBgHs8uS3O2i+mwJmilFZZFOs/mnVUZ8mxxLWW3uVcHm/TOQVCRI=,iv:xwLVcBTIblnpBCV+SoBs26WnfTThQgaRh+AR8FKhDp0=,tag:1LTbUnS5Uo/Ywmi33NxXzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
