# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: database
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:TGpwsgm53lw=,iv:ZP+uhMizdzd1iDAa15pqJL9lWNsCVKgQFLZjwpVbfAI=,tag:intJFOxjPbQcOhtMRtkq5Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vSOiZQwq+p2GejBtFgDNKhZWqvDr/xjhgQFwvQ==,iv:8UW5wnoBAeVZ54/UpsNA7Ir5j16PTp3a7rTSsuMirWk=,tag:fONGpepBtDErHc/FqmRZxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zy2rt7cnlaqg9r85w8d88zstjljcpr5cwnx35vp96l4nkzf9e9mqfqenvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0xjSVdac085ZThmV1ZB
            d0V4bEZQY3hvSlN4cjNGNXFMWVE5dVBvb0E0CndiQVN3dTUyZVVOMS8xOXpEa0p3
            bGluSUNrVGZIa1hZTTAwMXJtZjFBUmsKLS0tIFlpWnJ5WWpQU1YzbE9WY0U1YWY5
            dkFuNlQ0SStHYlo4TGFzY2lNSHY0OGMKWyrjrDVEUEEEJbEEiZuKPrVXO5k3urd7
            cY1b5AWhq8U2D2EwvbiwwURBRvLqBeDsZ8C10/sElzit3InCOjS7CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T18:01:49Z"
    mac: ENC[AES256_GCM,data:Ir1zjQlwwDYrzyISHxC6klrcBG9tCOLl11snz0l/KJA+h6Y7Eg+ukzu1QmvXAkpBPvtSYRNG181ieTA6PN67cDnKZ7iCj10BGxiL1mOIXKYabr/ZuAchGGtirFBLI+yQmR5dnGqeU0aLanr43+10XvyJ49K5YIx3RKIYlYrCM/g=,iv:7hZ2Vpy/FqlbqTVHE7h2NL4yf7wEXgj95akR6z7cyo4=,tag:cpTlBxZEgICP1YmlzIfbkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
